---
- name: Run uptime on all hosts
  hosts: all
  gather_facts: no

  tasks:
    - name: Execute uptime command
      ansible.builtin.command: uptime
      register: uptime_result

    - name: Show uptime output
      ansible.builtin.debug:
        var: uptime_result.stdout
    - name: df
      command: "df -h"
      register: df
    - name: output of df
      ansible.builtin.debug:
        var: df.stdout
    - name: touch file
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=enforcing'
    - name: see file
      command: 'cat /etc/selinux/config'
      register: out
    - name: debug config out
      debug:
        var: out.stdout
      
